### ISSUE TITLE
execute() return null immediately without errors or visible captcha. isReady = true. Ideas?

### ISSUE THREAD

**Issue by AndrewBotalov80** [bharathraj-e/g_recaptcha_v3#18]
The example project and my project return null immediately after calling execute. isReady = true
![SCR-20241228-igdg](https://github.com/user-attachments/assets/ad8214a2-8fa0-4b4e-bd8c-23dae9d1d579)
![SCR-20241228-igux](https://github.com/user-attachments/assets/6d08cfa7-25ba-4086-9e57-b85f5d3f6357)

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.27.1, on macOS 15.2 24C101 darwin-arm64, locale ru-RU)
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0-rc3)
[✓] Xcode - develop for iOS and macOS (Xcode 16.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] VS Code (version 1.96.2)
[✓] Connected device (5 available)
```

pubspec
```
name: g_recaptcha_v3_example
description: Demonstrates how to use the g_recaptcha_v3 plugin.

publish_to: 'none'

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  g_recaptcha_v3: ^1.0.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

```

Sometimes I can see a test with a selection, but the value is still null even before any interaction 😭
